### ISSUE TITLE
It is not working for me on Macos I am doing something wrong

### ISSUE THREAD

**Issue by aayestashn** [dreamsofcode-io/home-row-mods#5]
I did the following and it did not work.
- I installed cargo in my mac
- I installed kanata with `cargo install kanata`
- I installed [Karabiner-DriverKit-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/main/dist/Karabiner-DriverKit-VirtualHIDDevice-3.1.0.pkg) 3.1.0

- I ran this in the terminal `/Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate`
- I created the list file like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>com.my-user.kanata</string>
		<key>ProgramArguments</key>
		<array>
			<string>/Users/my-user/.cargo/bin/kanata</string>
			<string>-c</string>
			<string>/Users/my-user/dotfiles/.config/kanata/kanata.kbd</string>
		</array>
		<key>RunAtLoad</key>
		<true/>
		<key>KeepAlive</key>
		<true/>
		<key>StandardOutPath</key>
		<string>/Library/Logs/Kanata/kanata.out.log</string>
		<key>StandardErrorPath</key>
		<string>/Library/Logs/Kanata/kanata.err.log</string>
	</dict>
</plist>
```
- Then I copied the plist file to the LaunchDaemons folder and I tried to start the kanata
- `sudo cp ./com.my-user.kanata.plist /Library/LaunchDaemons`
- `sudo launchctl load /Library/LaunchDaemons/com.my-user.kanata.plist`
- `sudo launchctl start com.my-user.kanata`
- The file ` /Library/Logs/Kanata/kanata.err.log` is printing this
```
Error: failed to open keyboard device(s): Couldn't register any device

libc++abi: terminating

IOHIDDeviceOpen error: (iokit/common) not permitted

2024-11-03T18:15:23.017613-03:00 [0m[31m[ERROR] [0mfailed to open keyboard device(s): Couldn't register any device
```
But if I run kanata manually it works fine:
- `sudo /Users/my-user/.cargo/bin/kanata -c /Users/my-user/dotfiles/.config/kanata/kanata.kbd`

Any help is welcome.

**Comment by aayestashn** [comment]
I was able to fix the problem by doing the following. 
```sh
echo "$(whoami) ALL=(ALL) NOPASSWD: /Users/my-user/.cargo/bin/kanata" | sudo tee "/etc/sudoers.d/kanata" >/dev/null
# then unload the script
sudo launchctl unload /Library/LaunchDaemons/com.my-user.kanata.plist
# load again
sudo launchctl load -w /Library/LaunchDaemons/com.my-user.kanata.plist
```
And  then I added the kanata binary to system settings -> privacy security -> input monitoring

More details here -> https://www.reddit.com/r/ErgoMechKeyboards/comments/1fojvif/comment/lv3er4z/

**Comment by aryrabelo** [comment]
@aayestashn I did using Karabiner elements, Here is the Gist or the v1.0 (I'm still improving this)
https://gist.github.com/aryrabelo/211b811462968d26bd6b98f6d9842080

https://genesy.github.io/karabiner-complex-rules-generator/#eyJ0aXRsZSI6IkhvbWUgcm93IG1vZC10YXAga2V5cyIsInJ1bGVzIjpbeyJkZXNjcmlwdGlvbiI6IkhvbWUgcm93IG1vZC10YXAga2V5cyB3aXRoIHRhcCBvbiBob2xkIiwicGFyYW1ldGVycyI6eyJiYXNpYy50b19pZl9hbG9uZV90aW1lb3V0X21pbGxpc2Vjb25kcyI6NDAwLCJiYXNpYy50b19pZl9oZWxkX2Rvd25fdGhyZXNob2xkX21pbGxpc2Vjb25kcyI6MjUwfSwibWFuaXB1bGF0b3JzIjpbeyJ0eXBlIjoiYmFzaWMiLCJmcm9tIjp7ImtleV9jb2RlIjoiYSIsIm1vZGlmaWVycyI6eyJvcHRpb25hbCI6WyJhbnkiXX19LCJ0byI6W3sia2V5X2NvZGUiOiJhIn1dLCJ0b19pZl9oZWxkX2Rvd24iOlt7ImtleV9jb2RlIjoibGVmdF9ndWkifV19LHsidHlwZSI6ImJhc2ljIiwiZnJvbSI6eyJrZXlfY29kZSI6InMiLCJtb2RpZmllcnMiOnsib3B0aW9uYWwiOlsiYW55Il19fSwidG8iOlt7ImtleV9jb2RlIjoicyJ9XSwidG9faWZfaGVsZF9kb3duIjpbeyJrZXlfY29kZSI6ImxlZnRfb3B0aW9uIn1dfSx7InR5cGUiOiJiYXNpYyIsImZyb20iOnsia2V5X2NvZGUiOiJkIiwibW9kaWZpZXJzIjp7Im9wdGlvbmFsIjpbImFueSJdfX0sInRvIjpbeyJrZXlfY29kZSI6ImQifV0sInRvX2lmX2hlbGRfZG93biI6W3sia2V5X2NvZGUiOiJsZWZ0X3NoaWZ0In1dfSx7InR5cGUiOiJiYXNpYyIsImZyb20iOnsia2V5X2NvZGUiOiJmIiwibW9kaWZpZXJzIjp7Im9wdGlvbmFsIjpbImFueSJdfX0sInRvIjpbeyJrZXlfY29kZSI6ImYifV0sInRvX2lmX2hlbGRfZG93biI6W3sia2V5X2NvZGUiOiJsZWZ0X2NvbnRyb2wifV19LHsidHlwZSI6ImJhc2ljIiwiZnJvbSI6eyJrZXlfY29kZSI6ImoiLCJtb2RpZmllcnMiOnsib3B0aW9uYWwiOlsiYW55Il19fSwidG8iOlt7ImtleV9jb2RlIjoiaiJ9XSwidG9faWZfaGVsZF9kb3duIjpbeyJrZXlfY29kZSI6InJpZ2h0X2NvbnRyb2wifV19LHsidHlwZSI6ImJhc2ljIiwiZnJvbSI6eyJrZXlfY29kZSI6ImsiLCJtb2RpZmllcnMiOnsib3B0aW9uYWwiOlsiYW55Il19fSwidG8iOlt7ImtleV9jb2RlIjoiayJ9XSwidG9faWZfaGVsZF9kb3duIjpbeyJrZXlfY29kZSI6InJpZ2h0X3NoaWZ0In1dfSx7InR5cGUiOiJiYXNpYyIsImZyb20iOnsia2V5X2NvZGUiOiJsIiwibW9kaWZpZXJzIjp7Im9wdGlvbmFsIjpbImFueSJdfX0sInRvIjpbeyJrZXlfY29kZSI6ImwifV0sInRvX2lmX2hlbGRfZG93biI6W3sia2V5X2NvZGUiOiJyaWdodF9vcHRpb24ifV19LHsidHlwZSI6ImJhc2ljIiwiZnJvbSI6eyJrZXlfY29kZSI6InNlbWljb2xvbiIsIm1vZGlmaWVycyI6eyJvcHRpb25hbCI6WyJhbnkiXX19LCJ0byI6W3sia2V5X2NvZGUiOiJzZW1pY29sb24ifV0sInRvX2lmX2hlbGRfZG93biI6W3sia2V5X2NvZGUiOiJyaWdodF9ndWkifV19XX1dfQ==

**Comment by aayestashn** [comment]
hey [aryrabelo](https://github.com/aryrabelo) thank you so much i will take a look.

**Comment by JirR02** [comment]
Hey @aayestashn,

Have a look at this issue: jtroo/kanata/issues/1211. I think the problem is that you did not set the Privileges for you Terminal and for kanata.

**Comment by elliottminns** [comment]
Hey @aayestashn, have you been able to get Kanata working by running it in the terminal first of all, or is it just not working with Launchctl?

**Comment by aayestashn** [comment]
Hey @elliottminns thanks for the reply, it is working fine by running it into the terminal like this `sudo /Users/my-user/.cargo/bin/kanata -c /Users/my-user/dotfiles/.config/kanata/kanata.kbd`. The issue was the privileges like @JirR02 mentioned. 

> I was able to fix the problem by doing the following.
> 
> ```shell
> echo "$(whoami) ALL=(ALL) NOPASSWD: /Users/my-user/.cargo/bin/kanata" | sudo tee "/etc/sudoers.d/kanata" >/dev/null
> # then unload the script
> sudo launchctl unload /Library/LaunchDaemons/com.my-user.kanata.plist
> # load again
> sudo launchctl load -w /Library/LaunchDaemons/com.my-user.kanata.plist
> ```
> 
> And then I added the kanata binary to system settings -> privacy security -> input monitoring
> 
> More details here -> https://www.reddit.com/r/ErgoMechKeyboards/comments/1fojvif/comment/lv3er4z/
